### ISSUE TITLE
Fog doesnt look like fog.

### ISSUE THREAD

**Issue by Mr-Sisyphus** [ScreteMonge/3D-Weather#10]
Fog just doesn't feel like fog to me, looks like stink lines or wind that doesnt move or even smoke.
a better fit for it in my opinion would be to make it windy weather instead and make the animation of the fog travel in a set direction to kind of emulate a gust of wind moving across the screen instead of moving randomly. 
or the option to disable certain weather cycles, like fog really takes me out of it and ruins the immersion that the other weather cycles bring.
I dont know if theres much you can do with fog due to the issues with the skybox and having to compete with more popular HD plugins.

**Comment by ScreteMonge** [comment]
Fog will be toggle-able and set off by default in the next update
