### ISSUE TITLE
Feature Request: compact overlay

### ISSUE THREAD

**Issue by felixboons** [ScreteMonge/3D-Weather#12]
Is it possible to implement a compact overlay variant? It could have smaller icons and not display text.

**Comment by ScreteMonge** [comment]
I'll put it on the list of things to do. In general, I'd like to do a small rework of the overlay, so throwing a mini version in there at the same would make sense. Not a huge priority at the moment though

**Comment by dezefelix** [comment]
Sounds good. Thanks and good work.

I would like to add: the background of the overlay is a certain style, while other plugins have a transparent background and subtle borders. I've got no clue how this works and if this is an option in the RuneLite API or whatever, but if I could have your plugin overlay in the same style as those others (and in a compact variant), I will most likely always have it open to enhance my game experience. :)

**Comment by ScreteMonge** [comment]
Yeah I was having a problem getting the icons to work with the default RL borders/background. I've probably just not looked deep enough into it. I think, in general, moving from my custom border to the RL default would be beneficial

**Comment by ScreteMonge** [comment]
I've updated the main overlay to the proper RuneLite style as well as a mini/compact version

**Comment by felixboons** [comment]
Nice. I'll be using the mini version. Looks good and it's not too big. Thx :]
