### ISSUE TITLE
Ability to enable only certain weather types, but keep dynamic

### ISSUE THREAD

**Issue by scorgn** [ScreteMonge/3D-Weather#13]
I would love to be able to keep the weather dynamic, but still enable only certain weather types. For example, I really like rainy, stormy, and snowy, but not a huge fan of cloudy, starry, or foggy. It would be perfect if I could just uncheck "cloudy", "starry" and "foggy" from the list of weather types that are chosen.

I can help implement it if that's something we'd be interested in implementing.

**Comment by ScreteMonge** [comment]
Hey, apologies for the late reply. I currently only actively monitor my discord for bugfixes and suggestion (which should now be the default support link).

In the config, you can uncheck all three of those options you've named. I could add other options to remove other weathers (like rainy, snowy, stormy, etc), but I assume those are the ones you (and others) are happier with.
