### ISSUE TITLE
Feature Request: Additional Ambiences.

### ISSUE THREAD

**Issue by Rainblu** [ScreteMonge/3D-Weather#16]
I absolutely love the plug in, thank you for creating it and making the game more immersive. 

Was curious if additional ambience could be added, for when its sunny you can hear the sound of crickets/birds. Or windchimes during summer/windy?

Example: https://freesound.org/people/Nikodemus_Christian/sounds/266632/

Thank you again.

**Comment by ScreteMonge** [comment]
Sorry for the late response.

I've always thought an ambience plugin would be really neat, but it's hard to say whether it's something that should be packaged into a Weather plugin or not. At one point I had a couple more ambient tracks playing but it felt out of place for me to do so when the title of the plugin is "3D Weather." I could see it being a nice alternative plugin - but probably one for another creator to figure out

**Comment by Rainblu** [comment]
Thank you for the response, and yeah that makes sense. I was jus thinking cause rain/thunder has sound effects for them summer could have something similar.

Thank you again for the response and plug in all together 💯
