### ISSUE TITLE
Longer time loading chunks in Chambers of Xeric

### ISSUE THREAD

**Issue by samuel123g** [ScreteMonge/3D-Weather#18]
Taking about 2 seconds to load chunks and when walking into raid with the 3D Weather plugin on, does not happen with plugin turned off. Attached video for reference.

https://github.com/ScreteMonge/3D-Weather/assets/74942713/01621462-810c-45df-9050-37e0f1813bd6

And my settings at the time of recording:
![image](https://github.com/ScreteMonge/3D-Weather/assets/74942713/5e51d415-27c4-4ec5-8db3-5690c2bae451)

**Comment by granpawalton** [comment]
im experiencing this same issue in corrupted gauntlet for each room lit up

**Comment by PattyRich** [comment]
I get the issue on any chunk load.  Teleports etc. def an issue

**Comment by Felanbird** [comment]
The change that broke this has been reverted by the Runelite devs, by request of the plugin creator. 

It will likely be re-fixed when they have time.
