### ISSUE TITLE
Long time loading any new area every 15-20 tiles

### ISSUE THREAD

**Issue by samhoyle123** [ScreteMonge/3D-Weather#19]
It's really bad the last 24 hours. All zones.

**Comment by Odzinic** [comment]
I was experiencing this in almost every instance or underground area. Caused load times to take about 5-6 seconds instead of the normal 1-2 when the plugin is disabled.

**Comment by samhoyle123** [comment]
Im hoping they fix it soon, it's one of my favorite plugins. Probably my favorite as far as added ambiance goes.

**Comment by Felanbird** [comment]
The change that broke this has been reverted by the Runelite devs, by request of the plugin creator. 

It will likely be re-fixed when they have time.
