### ISSUE TITLE
Audio doesn't stop when switching between different weather

### ISSUE THREAD

**Issue by Emmsii** [ScreteMonge/3D-Weather#2]
When it starts raining and the sound effects start playing, the sounds don't stop when leaving a rainy biome.

**Comment by ScreteMonge** [comment]
How did you change biomes? Was it by walking, teleporting, or how else?

**Comment by Emmsii** [comment]
I've noticed it walking and teleporting so far. The sounds effects will fade off after a while.

**Comment by ScreteMonge** [comment]
Alright, I've put a potential fix in the queue for review. Should hopefully go live in a couple days

**Comment by ScreteMonge** [comment]
Update should be live. Leaving this open for the time being if anyone else has similar reports post-update

**Comment by Emmsii** [comment]
That seems to be working better now, thanks!
