### ISSUE TITLE
Feature request: Individual density settings (specifically for clouds)

### ISSUE THREAD

**Issue by VladiMatt** [ScreteMonge/3D-Weather#21]
I love the high density weather so much, but specifically the clouds TANK my performance. I'd love to be able to configure the density of clouds separately so I can keep them enabled on high density without dropping my FPS to sub 20.

**Comment by ScreteMonge** [comment]
Thanks for the suggestion. Shouldn't be super difficult to do and it's something I'd personally like

**Comment by ScreteMonge** [comment]
Added
