### ISSUE TITLE
suggestion/feature request

### ISSUE THREAD

**Issue by Squimbert** [ScreteMonge/3D-Weather#24]
can you make it so ambient sounds from the plugin turn off when OSRS ambient sounds are turned off in game? or maybe a toggleable option to do so?

**Comment by ScreteMonge** [comment]
I don't want to tie them together in case someone wants 3D weather ambience without in-game ambience. A toggle is possible, but a better solution might be to try include another sound option within the main audio menu specific to 3D weather (so alongside game ambience, music, etc)
