### ISSUE TITLE
Doing Continued Rooftop Agility Laps Unloads Objects

### ISSUE THREAD

**Issue by 3-X** [ScreteMonge/3D-Weather#26]
Black tiles gradually appear underneath boats in fremennik and fish sack agility end object disappears when doing laps on the rooftop agility course, usually after doing rooftop laps for a little while, 15-20ish laps

![image](https://github.com/ScreteMonge/3D-Weather/assets/52710506/48b85ee0-ef8a-4fe3-8ab4-0a139033b3ac)

starts with 1 or 2 tiles and gets worse every transition between overworld and rooftop until all are missing as seen above

how it starts
![image](https://github.com/ScreteMonge/3D-Weather/assets/52710506/6c7617aa-5ecd-4f87-9093-5fd1d840f335)

happens on other courses as well
![image](https://github.com/ScreteMonge/3D-Weather/assets/52710506/f336f226-cc0b-4fa1-afe1-e3b3b194d000)

also does this without 117hd being active as well just to clarify
![image](https://github.com/ScreteMonge/3D-Weather/assets/52710506/9bc3d44f-c8fd-4718-aa73-ffe24851e27a)

it seems to be the same objects/tiles every time that get unloaded

Thank you!

**Comment by 3-X** [comment]
On doing some more testing it seems to start happening when it rains/storms, possibly hitting a max on screen object counter causing the game to force unload certain objects?

**Comment by ScreteMonge** [comment]
Sorry for the delay, this should now be resolved. The fix isn't free of its own problems but they're probably less notable than this bug. We'll see if anyone notices them, but if not, this fix is here to stay
