### ISSUE TITLE
Weather locked to snow

### ISSUE THREAD

**Issue by ghost** [ScreteMonge/3D-Weather#29]
I've noticed of recent I've only seen snow as my weather from 3DW. I believe this is likely linked to the season type setting. It is currently set to dynamic and thus I believe it think's it's winter and must snow. However I'd like some viarety on the weather produced. Is it possible to give an "Disable" option for season type? So that it may produce any weather at any time of year?

**Comment by ScreteMonge** [comment]
Should be fixed now.
