### ISSUE TITLE
Biome is incorrect when season type is set to winter

### ISSUE THREAD

**Issue by Daggerdoc** [ScreteMonge/3D-Weather#30]
Hey! So I noticed I was having lots of continuous snow so I opened the overlay and noticed some weird places where set to the iceberg biome. Idk if that's what its called but it's the one with the 3 floating ice blocks. 

The biome of places like Lumbridge and Varrock change to that biome when set to winter, dynamic, or HD 117. When Spring, Summer, or Autumn are selected the biome changes back to the location's normal one.

**Comment by ScreteMonge** [comment]
Yep, looks like the Biome algorithm has broken. I'll work on a fix

**Comment by ScreteMonge** [comment]
Should now be fixed
