### ISSUE TITLE
mod conflict with the Citizens plugin

### ISSUE THREAD

**Issue by car357** [ScreteMonge/3D-Weather#33]
when it rains I've noticed in Varrock square the text from the citizens drops above their head. I'm not sure if this can be fixed however the other plugin isn't developed anymore. Would appreciate this fix as the citizens plugin also makes the game seem so much more alive.

**Comment by ScreteMonge** [comment]
Not really anything that can be done there unfortunately, even if Citizens was still being maintained I don't know if a fix is actually possible given that the two plugins can't directly read each other.
