### ISSUE TITLE
Location of raindrops is too consistent

### ISSUE THREAD

**Issue by Trottero** [ScreteMonge/3D-Weather#4]
I really like this plugin but there are some things which I would love to see changed / fixed.

It looks like a certain pattern is being cycled, so I see a lot of patterns returning (specifically for the rain drops) which really bugs me when I'm in the same area for a little bit.

Included video:
https://gyazo.com/4e3e1a80f0dc5625555eb924fae05416

Especially in the bottom right you can see this pattern of 2 drops repeating every so often.

**Comment by ScreteMonge** [comment]
Thanks for the request.

So the way the plugin works is it spawns an object on a tile and animates it - this is for all objects regardless of the weather. This animation loops until the object is despawned. The animation itself is two raindrops falling one after the other, which, when looped, creates a very predictable pattern. Every once in a while, the object will then be relocated to a different tile, where it will begin animating and looping again.

So the short of it is that, given this, I'll need a little more info from you. Is the simple looping animation itself bothering you, or that the objects don't move from their tiles fast enough?

**Comment by Trottero** [comment]
The simple looping animation should be fine, as long as there's enough variance in offset between all other raindrops, it currently looks like there's a wave of rain drops all coming down at the same time, then the next wave, and another wave (repeat 5-6 times) and then another cycle begins.

Them not moving fast enough also feels unnatural to me.

**Comment by Hibbs6** [comment]
I think it might look a lot more natural if it looped for less time and switched which tile it was on more often. Something that might also help a lot would be adding a few different animations if that is possible.

**Comment by ScreteMonge** [comment]
The next update I'm working on will properly scale the frequency with which all objects are relocated to the number of objects spawned, which should help with this. Previously, even at Highest weather density, only 50 objects would relocate at a time.

Now, each weather type is given a "relocation rate" - in other words, how often a group of objects will be relocated. For Storm, objects will relocate every tick to give a more frantic look to how fast the rain moves around. Rain is currently at 2 ticks, and something like Fog is around 16 ticks (if Fog objects relocated every tick it would look absurdly busy). Again, hopefully scaling the relocation number will resolve this issue, but if not, I can bump Rain down 1 tick to equal Storm.

As for different animations: you can't add animations or models of your own to RuneLite. Therefore, I'm restricted to what's available in the cache. This current model/animation combo is the only one remotely like it and the best option by far. It's unfortunate for sure, but in the future who knows how this may change.

**Comment by ScreteMonge** [comment]
Object groups have been expanded to account for how dense the weather is, so more objects will relocate at one time. More object variations have also been added which should help resolve this issue. Please let me know how well it works
